import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {LogoInfoContextProvider} from "@/providers/logoInfo-provider";
import {OrderDetailsProvider} from "@/providers/orderItemDetail-provider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
                   
                        <OrderDetailsProvider>
                            <LogoInfoContextProvider>
                                {children}
                            </LogoInfoContextProvider>
                        </OrderDetailsProvider>
                    
            </body>
    </html>
  );
}
